---
title: "nyc_taxi"
author: "Robert McKenzie"
date: "November 27, 2018"
output: html_document
---

```{r setup, include=FALSE, cache = TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(lubridate)
library(fs)
library(rgdal)

names_18 <- dir_ls("cab_2018")

cab_data18 <- map_dfr(names_18, fread, .id = "source")

cab_data18 <- cab_data18[sample(100000000), ]

write_rds(cab_data18, "taxi_data_jan-mar")

tips <- cab_data18 %>%
  select("V3", "V4", V5, V10, V14, "V17")

tips <- tips %>%
  separate(V3, into = c("date", "time"), sep = " ") %>%
  mutate(date = ymd(date),
         time = hms(time)) %>%
  rename(time = "time", "num_pass" = V4, "dist" = V5, "payment_type" = V10, "tip" = V14, "total" = V17) %>%
  mutate(tip_per = tip / total) 

mean_tip_per <- tips %>%
  na.omit(tip_per) %>%
  summarize(mean(tip_per)) 

mean_tip <- tips %>%
  summarize(mean(tip))

cash_tip_per <- tips %>%
  na.omit(tip_per) %>%
  filter(payment_type == "2") %>%
  summarize(mean(tip_per)) 

cash_tip <- tips %>%
  na.omit(tip_per) %>%
  filter(payment_type == "2") %>%
  summarize(mean(tip)) 


card_tip_per <- tips %>%
  na.omit(tip_per) %>%
  filter(payment_type == "1") %>%
  summarize(mean(tip_per))

card_tip <- tips %>%
  na.omit(tip_per) %>%
  filter(payment_type == "1") %>%
  summarize(mean(tip)) 


pass_model <- lm(formula = V14 ~ V4, data = cab_data18)

dist_model <- lm(tip_per ~ dist, tips)

summary(pass_model)
summary(dist_model)

```

The average tip of a NYC cab ride in the first three months of 2018 was `r mean_tip$1`, which was `r mean_tip_per$1` % of the total fare.



```{r}

library(leaflet)
library(raster)
library(rgeos)

taxi_zone_lookup <- read_csv("taxi _zone_lookup.csv")
tiles <- readOGR("taxi_zones", "taxi_zones")

projection(tiles) = "+init=epsg:2263"
tiles2 = spTransform(tiles, "+init=epsg:4326")

labels <- tiles2$zone

pickup <- cab_data18 %>%
  dplyr::select(V2, V3, V8, V9) %>%
  complete(V8 = 1:263) %>%
  count(V8)

zone_count <- log(pickup$n, base = 50)

leaflet(tiles2) %>% 
  addTiles() %>% 
  addPolygons(fillOpacity = 0.75, weight = 3, label = labels, color = ~pal(zone_count),
              highlightOptions = highlightOptions(color = "white", weight = 5, bringToFront = TRUE))

tiles2@data <- tiles2@data %>%
  mutate(count = zone_count)

pal <- colorNumeric(
  palette = "Blues",
  domain = (tiles2$count))
```

